services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build:
      context: .
    image: capellawish/app
    command: sh -c 'uv run --no-dev manage.py collectstatic --noinput && uv run --no-dev manage.py migrate && hypercorn capellawish.asgi:application --config ./hypercornconfig.toml'
    volumes:
      # - .:/app # Uncomment for local development
      - webstatic:/app/static
      - weblog:/app/logs
      - webmedia:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  nginx:
    image: macbre/nginx-http3:latest
    ports:
      - '8000:80/tcp'
      - '8000:80/udp'
      - '8081:443/tcp'  # Expose HTTPS
      - '8081:443/udp'
    # configuration
    restart: always
    user: '0:0' # run as root to bind low ports
    volumes:
      - ./nginxdev.conf:/etc/nginx/nginx.conf:ro
      - webstatic:/static:ro
      - webmedia:/media:ro
      - weblog:/var/log/nginx
      - ./certs:/etc/nginx/certs:ro  # Mount SSL certs
    depends_on:
      - web
  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes --protected-mode yes
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  celeryworker:
    image: capellawish/app
    restart: always
    command: sh -c "celery -A capellawish worker -l info --concurrency=2"
    volumes:
      - weblog:/app/logs
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
  flower:
    image: mher/flower:latest
    restart: always
    command: sh -c "celery flower -A capellawish --port=5555"
    env_file:
      - .env
    ports:
      - '5950:5555'
    depends_on:
      - web
      - redis
      - db
      - celeryworker
volumes:
  postgres_data:
  webstatic:
  weblog:
  webmedia:
  redis_data:
